#!/bin/bash


all="no"
msg="update"

set -e

for p in $@
do
	if [ $p = "all" ]; then
		all="yes"
	else
		msg="$p"
	fi
done


if [ "$all" = "yes" ]; then 
git add -A
fi

git commit -m "$msg"
git push 
